### ISSUE TITLE
Document how to start truffle tests for this structure of contracts

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/oracles-contract#19]
```
viktors-MacBook-Pro:oracles-contract viktor$ truffle test
Error: Could not find oracles-contract-key/KeyClass.sol from any sources; imported from /Users/viktor/Documents/HintsProjects/BlockNotary/Oracles/oracles-contract/contracts/KeysManager.sol
    at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:69147:23
    at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:165637:16
    at next (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:178009:18)
    at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:69135:7
    at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:202146:5
    at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:177914:16
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:165607:25)
    at iterateeCallback (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:165597:17)
    at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:165637:16
    at ReadFileContext.callback (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:202142:14)
```

**Comment by vbaranov** [comment]
@lorien could you add some lines in readme, how to start truffle tests for Oracles contracts?

**Comment by lorien** [comment]
See https://github.com/oraclesorg/oracles-contract/commit/6651f4a62aa9032516704ac715c701f39c05fdfd
